dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  scan:
    base-packages: com.github.zhanjixun.**.service
spring:
  application:
    name: spring-boot-dubbo-demo-biz
server:
  port: 8081